on:
  schedule:
    - cron: "57 23 * * *"
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: install som dependencies
        run: |
          pip install pillow numpy ffmpeg-python google-auth google-auth-oauthlib google-api-python-client

      - name: restore creds
        run: |
          echo "$CREDS" > credentials.json
          echo "$TOKEN" | base64 -d > token.pickle
        env:
          CREDS: ${{ secrets.CREDS }}
          TOKEN: ${{ secrets.TOKEN }}

      - name: upload
        run: python uplM.py
